# Cloudflare Pages Configuration
name = "namesentry"
compatibility_date = "2023-10-30"

[build]
command = "npm run build"
cwd = "."
watch_dir = "."

[env.production.vars]
NODE_ENV = "production"

[env.preview.vars]
NODE_ENV = "preview"