name = "namesentry"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[build]
command = "npx @cloudflare/next-on-pages@1"

[env.production]
NODE_ENV = "production"

[env.preview]
NODE_ENV = "preview"